### ISSUE TITLE
Turn off debug in your demo

### ISSUE THREAD

**Issue by pydanny** [iyanuashiri/meethub#7]
https://themeethub.herokuapp.com/asdasdasd shows me a DEBUG error page

**Comment by bilelmoussaoui** [comment]
Or just add a 404 error page :)

**Comment by pydanny** [comment]
No no no, don't "just add an error page". That's the wrong way. `DEBUG` should never be on in a production setting.

**Comment by bilelmoussaoui** [comment]
@pydanny Yeah I know. But an error page is required too.

**Comment by dminca** [comment]
It's just a demo ffs, will you calm down

**Comment by pydanny** [comment]
@dminca We were asked for feedback. We gave it. Calmly and clearly, without use of angry abbreviations that you used such as "FFS".

I really have no idea why you are getting so worked up about this discussion.
